#!/usr/bin/env python3
"""
export_fingering.py — Export predicted fingering từ hệ thống ra 2 formats:

  1. fingering_report.txt  — bảng note-by-note (measure, beat, note, finger)
     dễ đọc, có GT comparison nếu có annotation gốc trong file.

  2. fingering_output.musicxml — file MusicXML gốc được inject fingering dự đoán
     vào <technical><fingering> elements, mở được trong MuseScore / Sibelius.

Usage:
    python scripts/export_fingering.py [input.musicxml] [output_dir]

Default:
    input  = test_file/FN7ALfpGxiI.musicxml
    output = test_file/
"""

import sys
import os
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))

from fingering.io.musicxml_reader import MusicXMLReader
from fingering.phrasing.pipeline import PhraseAwareFingering

NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

def note_name(pitch: int) -> str:
    return f"{NOTE_NAMES[pitch % 12]}{pitch // 12 - 1}"


# ──────────────────────────────────────────────────────────────
# 1. Text report
# ──────────────────────────────────────────────────────────────

def write_text_report(rh, lh, rh_fingering, lh_fingering, rh_phrases, lh_phrases, output_path):
    lines = []
    lines.append("=" * 70)
    lines.append("  AUTOMATIC PIANO FINGERING REPORT")
    lines.append(f"  Generated by PhaseAwareFingering v2 (2026-03-05)")
    lines.append("=" * 70)

    def hand_section(notes, fingering, phrases, label):
        lines.append(f"\n{'─' * 70}")
        lines.append(f"  {label}  ({len(notes)} notes, {len(phrases)} phrases)")
        lines.append(f"{'─' * 70}")

        # Phrase summary
        lines.append(f"\n  PHRASES:")
        for p in phrases:
            if not p.notes:
                continue
            role = getattr(p, 'period_role', '') or ''
            lines.append(
                f"    P{p.id+1:02d}  m{p.notes[0].measure:>3}→m{p.notes[-1].measure:>3}  "
                f"{p.intent.name:<12s}  arc={p.arc_type.name:<5s}  "
                f"notes={len(p.notes):>3}  {role}"
            )

        lines.append(f"\n  NOTE-BY-NOTE FINGERING:")
        lines.append(f"  {'Meas':<5} {'Beat':<5} {'Note':<6} {'Finger':<7} {'GT':<5} {'Match'}")
        lines.append(f"  {'─'*4} {'─'*4} {'─'*5} {'─'*6} {'─'*4} {'─'*5}")

        matches = total_gt = 0
        for i, (note, finger) in enumerate(zip(notes, fingering)):
            gt = note.finger
            if gt is not None:
                total_gt += 1
                match_str = "✅" if gt == finger else "❌"
                if gt == finger:
                    matches += 1
            else:
                match_str = "  "
                gt = "-"
            lines.append(
                f"  m{note.measure:<4d} b{note.beat:<4.1f} {note_name(note.pitch):<6s} "
                f"f={finger}       {str(gt):<4s} {match_str}"
            )

        if total_gt > 0:
            mr = matches / total_gt * 100
            lines.append(f"\n  Match rate vs GT: {matches}/{total_gt} = {mr:.1f}%")

    hand_section(rh, rh_fingering, rh_phrases, "RIGHT HAND (Staff 1 — Treble)")
    hand_section(lh, lh_fingering, lh_phrases, "LEFT HAND  (Staff 2 — Bass)")

    lines.append(f"\n{'=' * 70}\n")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"  ✓ Text report  → {output_path}")


# ──────────────────────────────────────────────────────────────
# 2. MusicXML with injected fingering
# ──────────────────────────────────────────────────────────────

def write_musicxml_with_fingering(input_xml, rh, lh, rh_fingering, lh_fingering, output_path):
    """
    Inject predicted fingering numbers back into the MusicXML.

    Strategy:
      - Build a lookup: (measure, beat_rounded, pitch, hand) → predicted_finger
      - Walk all <note> elements in the XML; for each non-rest note,
        find the matching NoteEvent and inject <technical><fingering> tag.
    """
    tree = ET.parse(input_xml)
    root = tree.getroot()

    ns = ''
    if root.tag.startswith('{'):
        ns = root.tag.split('}')[0] + '}'

    def tag(name): return f'{ns}{name}'

    # Build lookup table
    lookup = {}
    for note, f in zip(rh, rh_fingering):
        key = (note.measure, round(note.beat, 2), note.pitch, 'right')
        lookup[key] = f
    for note, f in zip(lh, lh_fingering):
        key = (note.measure, round(note.beat, 2), note.pitch, 'left')
        lookup[key] = f

    STEP_TO_ST = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}
    _divisions = 1
    current_measure = 0
    staff_time = {}
    measure_beat_start = {}

    for measure_el in root.iter(tag('measure')):
        current_measure += 1
        for sn in staff_time:
            measure_beat_start[sn] = staff_time[sn]

        for child in measure_el:
            local = child.tag.replace(ns, '')

            if local == 'attributes':
                div_el = child.find(tag('divisions'))
                if div_el is not None:
                    _divisions = int(div_el.text)

            if local == 'note':
                staff_el = child.find(tag('staff'))
                staff_num = staff_el.text if staff_el is not None else '1'
                hand = 'right' if staff_num == '1' else 'left'

                if staff_num not in staff_time:
                    staff_time[staff_num] = 0.0
                    measure_beat_start[staff_num] = 0.0

                t = staff_time[staff_num]

                # Skip rests
                if child.find(tag('rest')) is not None:
                    dur_el = child.find(tag('duration'))
                    if dur_el is not None:
                        beats = int(dur_el.text) / _divisions
                        if child.find(tag('chord')) is None:
                            staff_time[staff_num] = t + beats
                    continue

                pitch_el = child.find(tag('pitch'))
                if pitch_el is None:
                    continue

                step = pitch_el.find(tag('step')).text
                octave = int(pitch_el.find(tag('octave')).text)
                alter_el = pitch_el.find(tag('alter'))
                alter = int(float(alter_el.text)) if alter_el is not None else 0
                midi_pitch = (octave + 1) * 12 + STEP_TO_ST[step] + alter

                dur_el = child.find(tag('duration'))
                dur_beats = int(dur_el.text) / _divisions if dur_el is not None else 0.5
                is_chord = child.find(tag('chord')) is not None
                note_onset = t if not is_chord else max(t - dur_beats, 0.0)

                mbs = measure_beat_start.get(staff_num, 0.0)
                beat_in_meas = round(note_onset - mbs + 1.0, 2)

                key = (current_measure, beat_in_meas, midi_pitch, hand)
                predicted_finger = lookup.get(key)

                if predicted_finger is not None:
                    # Find or create <notations><technical><fingering>
                    notations_el = child.find(tag('notations'))
                    if notations_el is None:
                        notations_el = ET.SubElement(child, 'notations')
                    technical_el = notations_el.find(tag('technical'))
                    if technical_el is None:
                        technical_el = ET.SubElement(notations_el, 'technical')
                    # Replace existing fingering if any
                    existing = technical_el.find(tag('fingering'))
                    if existing is not None:
                        technical_el.remove(existing)
                    f_el = ET.SubElement(technical_el, 'fingering')
                    f_el.text = str(predicted_finger)

                if not is_chord:
                    staff_time[staff_num] = note_onset + dur_beats

    # Fix namespace: ET may strip/mangle it during write. Use simple write.
    ET.register_namespace('', ns.strip('{}')) if ns else None
    tree.write(output_path, encoding='unicode', xml_declaration=True)
    print(f"  ✓ MusicXML     → {output_path}")


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────

def main():
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    input_xml = sys.argv[1] if len(sys.argv) > 1 else os.path.join(base_dir, 'test_file', 'FN7ALfpGxiI.musicxml')
    out_dir   = sys.argv[2] if len(sys.argv) > 2 else os.path.dirname(input_xml)

    os.makedirs(out_dir, exist_ok=True)
    base_name = os.path.splitext(os.path.basename(input_xml))[0]

    print(f"\n{'='*60}")
    print(f"  Automatic Piano Fingering — Export")
    print(f"  Input : {input_xml}")
    print(f"  Output: {out_dir}/")
    print(f"{'='*60}")

    # Parse
    reader = MusicXMLReader()
    rh, lh, tonic_pc, mode = reader.parse_grand_staff_with_key(input_xml)
    print(f"\n✓ Parsed: RH={len(rh)} notes, LH={len(lh)} notes  |  key tonic_pc={tonic_pc} ({mode})")

    # Run pipeline
    paf = PhraseAwareFingering(tonic_pc=tonic_pc)
    rh_fingering = paf.run(rh, companion_notes=lh)
    lh_fingering = paf.run(lh, companion_notes=rh)
    rh_phrases   = paf.get_phrases(rh, companion_notes=lh)
    lh_phrases   = paf.get_phrases(lh, companion_notes=rh)
    print(f"✓ Fingering done: RH={len(rh_phrases)} phrases, LH={len(lh_phrases)} phrases")

    print(f"\nExporting...")

    # 1. Text report
    txt_path = os.path.join(out_dir, f"{base_name}_fingering.txt")
    write_text_report(rh, lh, rh_fingering, lh_fingering, rh_phrases, lh_phrases, txt_path)

    # 2. MusicXML
    xml_path = os.path.join(out_dir, f"{base_name}_fingering.musicxml")
    write_musicxml_with_fingering(input_xml, rh, lh, rh_fingering, lh_fingering, xml_path)

    print(f"\nDone! Mở file sau trong MuseScore để xem ngón tay trên khuông nhạc:")
    print(f"  {xml_path}\n")


if __name__ == '__main__':
    main()
